spring:
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: config-client-1
config-client.message: Spring Cloud Config Repo says "Hello!" Test OK
