spring:
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: config-client-1
config-client.message: Made a change in the repo Test OK
